[WAVE-15] Ручки для сообщений и диалогов
radium-rtf/radium-backend pull request #46
Opened 2024-04-26 07:02 UTC by FUFSoB

2024-05-23 20:02 UTC, khostya requested changes

2024-05-24 05:41 UTC, FUFSoB commented on internal/wave/entity/content.go
> +		FileId *uuid.UUID
Видимо остался лишним в попытках успешного запуска.

2024-05-25 17:08 UTC, khostya commented on internal/wave/httpserver/handlers/chats/router.go
> +		r.Use(auth.UserId(tokenManager))
лучше использовать `auth.Required` у нас же эти хендеры доступныы только для неавторизованных, так не нужно будет в `internal/wave/httpserver/handlers/chats/internal/get/get.go` писать
```
if !ok {
			userId = uuid.Nil
			// resp.Error(r, w, resp.ErrUnauthorized)
			// return
		}
```

2024-05-25 17:09 UTC, khostya commented on internal/wave/httpserver/handlers/message/internal/send/request.go
> +	return d.ChatId, d.Content
я имел ввиду вообще геттеры не писать, геттеры же пишут когда поля приватные

2024-05-25 17:09 UTC, khostya commented on internal/wave/httpserver/handlers/message/router.go
> +		r.Use(auth.UserId(tokenManager))
auth.Required

2024-05-25 17:10 UTC, khostya commented on internal/wave/httpserver/handlers/message/router.go
auth.Required

2024-05-25 17:11 UTC, khostya commented on internal/wave/httpserver/handlers/user/router.go
auth.Required

2024-05-25 17:13 UTC, khostya commented on internal/wave/usecase/dialogue.go
> +	userId, ok := ctx.Value("userId").(uuid.UUID)
передавай userId как аргумент. и опять же проверка лишняя

2024-05-25 17:17 UTC, khostya commented on internal/wave/usecase/user.go
> +	userId, ok := ctx.Value("userId").(uuid.UUID)
тут тоже userId надо передавать как аргумент

2024-05-25 17:18 UTC, khostya commented on internal/wave/usecase/repo/postgres/message.go
> +		Where("dialogue_id = ?", chatId).
отсортируй

2024-05-25 17:21 UTC, khostya commented on internal/wave/usecase/repo/postgres/dialogue.go
> +func (r Dialogue) GetAllByUserId(ctx context.Context, userId uuid.UUID) ([]*entity.Dialogue, error) {
потом нужно будет доставать это из юзера через join(`Relation("Dialogues")`)

2024-05-25 17:24 UTC, khostya commented on internal/wave/httpserver/handlers/chats/internal/get/get.go
> +			userId = uuid.Nil
аналогично

2024-05-25 17:25 UTC, khostya commented on internal/wave/httpserver/handlers/routes.go
> +	chats.New(h, useCases)
мб разделить диалоги и чаты?

2024-05-25 17:34 UTC, khostya commented
л

2024-06-04 12:23 UTC, khostya commented on migrations/20240603164518_create_wave_groups.up.sql
> +    role TEXT,
text?

2024-06-09 12:02 UTC, FUFSoB commented on internal/wave/httpserver/handlers/message/internal/get/pins.go
> +// @Router       /v1/messages/{chatId}/pins [get]
Имеет смысл перенести в получение в виде фильтра? Или оно просто не нужно?

2024-06-11 16:11 UTC, merged